# Generated by Django 5.2 on 2025-04-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0002_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skills",
            name="skill_name",
            field=models.CharField(max_length=20),
        ),
    ]
